### ISSUE TITLE
Cannot sync or delete Google account after installing

### ISSUE THREAD

**Issue by Cleridwen** [openGiraffes/b2g-certificates#3]
Installation went fine on a Nokia 2720 Flip, KaiOS 2.5.2, using the .bat script on Windows, and now some apps that couldn't use internet before do work (like "ZAP for Reddit"), but not all, WhatsApp still won't connect for example, and some other odd behaviors are happening.

Notably, when opening the e-mail app, I get told that I need to re-authorize my account. When I press OK, I get put back on the previous screen, and the e-mail app freezes entirely.

In the settings, under Accounts, my Google account is here, but if I select it, then press "Delete" and confirm, nothing happens.

I'm not sure where to go from here

**Comment by LiarOnce** [comment]
I'm sorry for not replying until now.

This script is only used to add the root certificate to the certificate store in the system, and cannot solve the problems caused by service providers such as Google and WhatsApp and KaiOS Technology (e.g. termination of partnership).

If you are sure that the above issue is not the case, you can save their root certificates on any other system and store them in the `certs` folder (The file name extension is `*.pem`), then re execute the script.

**Comment by Cleridwen** [comment]
Oh, I see! Thank you for the reply. No worries for the delay.
I'm sorry I missed the point of that script. I don't exactly remember what I did since I opened this issue, but everything is functional now, I don't have the issues I originally described anymore.

Have a great day!
